import {formField} from 'tocco-app-extensions'

import SubGrid from './fromFieldFactories/subGrid'

export default {
  'binary': formField.formattedValueFactory('document'),
  'birthdate': formField.formattedValueFactory('birthdate'),
  'boolean': formField.formattedValueFactory('boolean'),
  'code': formField.formattedValueFactory('text'),
  'counter': formField.formattedValueFactory('string'),
  'data-amount': formField.formattedValueFactory('number'),
  'date': formField.formattedValueFactory('date'),
  'datetime': formField.formattedValueFactory('datetime'),
  'time': formField.formattedValueFactory('time'),
  'decimal': formField.formattedValueFactory('decimal'),
  'display': formField.formattedValueFactory('html'),
  'duration': formField.formattedValueFactory('duration'),
  'document': formField.formattedValueFactory('document'),
  'email': formField.formattedValueFactory('email'),
  'html': formField.formattedValueFactory('html'),
  'image': formField.formattedValueFactory('document'),
  'identifier': formField.formattedValueFactory('string'),
  'latitude': formField.formattedValueFactory('number'),
  'login': formField.formattedValueFactory('string'),
  'long': formField.formattedValueFactory('string'),
  'longitude': formField.formattedValueFactory('number'),
  'moneyamount': formField.formattedValueFactory('moneyamount'),
  'multi-remote-field': formField.formattedValueFactory('multi-remote'),
  'multi-select-box': formField.formattedValueFactory('multi-select'),
  'named-upload': formField.formattedValueFactory('document'),
  'integer': formField.formattedValueFactory('number'),
  'percent': formField.formattedValueFactory('number'),
  'phone': formField.formattedValueFactory('phone'),
  'pulldown-date': formField.formattedValueFactory('date'),
  'range': {
    date: formField.formattedValueFactory('date-range'),
    birthdate: formField.formattedValueFactory('date-range')
  },
  'remote': formField.formattedValueFactory('remote'),
  'search-filter': formField.formattedValueFactory('search-filter'),
  'single-remote-field': formField.formattedValueFactory('remote'),
  'single-select-box': formField.formattedValueFactory('single-select'),
  'sorting': formField.formattedValueFactory('number'),
  'string': formField.formattedValueFactory('string'),
  'text': formField.formattedValueFactory('text'),
  'text-area': formField.formattedValueFactory('text'),
  'upload': formField.formattedValueFactory('document'),
  'url': formField.formattedValueFactory('url'),
  'uuid': formField.formattedValueFactory('string'),
  'subTable': SubGrid
}
