import '@storybook/addon-knobs/register'
import '@storybook/addon-actions/register'
import '@storybook/addon-options/register'
import 'storybook-addon-intl/register'
import 'storybook-addon-styled-component-theme/dist/src/register'
import '@storybook/addon-backgrounds/register'
