import {formField} from 'tocco-util'
import SubGrid from './fromFieldFactories/subGrid'

export default {
  'ch.tocco.nice2.model.form.components.Form': null,
  'ch.tocco.nice2.model.form.components.Template': null,
  'ch.tocco.nice2.model.form.components.action.Action': null,
  'ch.tocco.nice2.model.form.components.action.ActionSeparator': null,
  'ch.tocco.nice2.model.form.components.composite.LocationField': null,
  'ch.tocco.nice2.model.form.components.layout.HorizontalBox': null,
  'ch.tocco.nice2.model.form.components.layout.VerticalBox': null,
  'ch.tocco.nice2.model.form.components.navigation.IteratorComponent': null,
  'ch.tocco.nice2.model.form.components.simple.BirthDateField': formField.editableValueFactory('birthdate'),
  'ch.tocco.nice2.model.form.components.simple.Checkbox': formField.editableValueFactory('boolean'),
  'ch.tocco.nice2.model.form.components.simple.CodeField': formField.editableValueFactory('text'),
  'ch.tocco.nice2.model.form.components.simple.ConstantField': null,
  'ch.tocco.nice2.model.form.components.simple.CreatePasswordField': null,
  'ch.tocco.nice2.model.form.components.simple.CustomDataField': null,
  'ch.tocco.nice2.model.form.components.simple.DataAmountField': formField.editableValueFactory('number'),
  'ch.tocco.nice2.model.form.components.simple.DateField': formField.editableValueFactory('date'),
  'ch.tocco.nice2.model.form.components.simple.DatetimeField': formField.editableValueFactory('datetime'),
  'ch.tocco.nice2.model.form.components.simple.DescriptionField': null,
  'ch.tocco.nice2.model.form.components.simple.DisplayExpressionFieldFacade': null,
  'ch.tocco.nice2.model.form.components.simple.DisplayField': null,
  'ch.tocco.nice2.model.form.components.simple.DocumentField': formField.editableValueFactory('document'),
  'ch.tocco.nice2.model.form.components.simple.DurationField': null,
  'ch.tocco.nice2.model.form.components.simple.EmailField': formField.editableValueFactory('email'),
  'ch.tocco.nice2.model.form.components.simple.HtmlField': formField.editableValueFactory('html'),
  'ch.tocco.nice2.model.form.components.simple.ImageField': formField.editableValueFactory('document'),
  'ch.tocco.nice2.model.form.components.simple.LoginField': formField.editableValueFactory('string'),
  'ch.tocco.nice2.model.form.components.simple.MoneyAmountField': formField.editableValueFactory('number'),
  'ch.tocco.nice2.model.form.components.simple.MultiRemoteField': formField.editableValueFactory('multi-remote'),
  'ch.tocco.nice2.model.form.components.simple.MultiSelectBox': formField.editableValueFactory('multi-select'),
  'ch.tocco.nice2.model.form.components.simple.NamedUploadField': formField.editableValueFactory('document'),
  'ch.tocco.nice2.model.form.components.simple.NumberField': formField.editableValueFactory('number'),
  'ch.tocco.nice2.model.form.components.simple.PasswordField': null,
  'ch.tocco.nice2.model.form.components.simple.PathField': null,
  'ch.tocco.nice2.model.form.components.simple.PercentField': formField.editableValueFactory('number'),
  'ch.tocco.nice2.model.form.components.simple.PhoneField': formField.editableValueFactory('phone'),
  'ch.tocco.nice2.model.form.components.simple.PulldownDateField': formField.editableValueFactory('date'),
  'ch.tocco.nice2.model.form.components.simple.RangeField': {
    'date': formField.editableValueFactory('date-range'),
    'birthdate': formField.editableValueFactory('date-range')
  },
  'ch.tocco.nice2.model.form.components.simple.RemoteField': formField.editableValueFactory('remote'),
  'ch.tocco.nice2.model.form.components.simple.SingleSelectBox': formField.editableValueFactory('single-select'),
  'ch.tocco.nice2.model.form.components.simple.TextArea': formField.editableValueFactory('text'),
  'ch.tocco.nice2.model.form.components.simple.TextField': formField.editableValueFactory('string'),
  'ch.tocco.nice2.model.form.components.simple.TimeField': null,
  'ch.tocco.nice2.model.form.components.simple.UploadField': formField.editableValueFactory('document'),
  'ch.tocco.nice2.model.form.components.simple.UrlField': formField.editableValueFactory('url'),
  'ch.tocco.nice2.model.form.components.simple.UuidField': formField.editableValueFactory('string'),
  'ch.tocco.nice2.model.form.components.table.Column': null,
  'ch.tocco.nice2.model.form.components.table.Table': SubGrid()
}
