import {H1, H2, H3, H4, H5, H6,
  StyledH1, StyledH2, StyledH3, StyledH4, StyledH5, StyledH6} from './Heading'
import {Dd, Dt, Dl, Li, Ol, Ul,
  StyledDd, StyledDt, StyledDl, StyledLi, StyledOl, StyledUl} from './List'
import {B, Code, Del, Em, I, Ins, Kbd, Mark, P, Pre, Q, S, Strong, Sub, Sup, U, Var,
  StyledB, StyledCode, StyledDel, StyledEm, StyledI, StyledIns, StyledKbd, StyledMark,
  StyledP, StyledPre, StyledQ, StyledS, StyledStrong, StyledSub, StyledSup, StyledU, StyledVar} from './Misc'
import Span, {StyledSpan} from './Typography'
import InjectFontRoboto from './Font'

export {
  B,
  Code,
  Dd,
  Del,
  Dl,
  Dt,
  Em,
  H1,
  H2,
  H3,
  H4,
  H5,
  H6,
  I,
  Ins,
  InjectFontRoboto,
  Kbd,
  Li,
  Mark,
  Ol,
  P,
  Pre,
  Q,
  S,
  Span,
  Strong,
  StyledB,
  StyledCode,
  StyledDd,
  StyledDel,
  StyledDl,
  StyledDt,
  StyledEm,
  StyledH1,
  StyledH2,
  StyledH3,
  StyledH4,
  StyledH5,
  StyledH6,
  StyledI,
  StyledIns,
  StyledKbd,
  StyledLi,
  StyledMark,
  StyledOl,
  StyledP,
  StyledPre,
  StyledQ,
  StyledS,
  StyledSpan,
  StyledStrong,
  StyledSub,
  StyledSup,
  StyledU,
  StyledUl,
  StyledVar,
  Sub,
  Sup,
  U,
  Ul,
  Var
}
