CYPRESS_USER={{CYPRESS_USER}}
CYPRESS_PASSWORD={{CYPRESS_PASSWORD}}
CYPRESS_API_KEY={{CYPRESS_API_KEY}}
CYPRESS_USER_PASSWORD_HASH={{CYPRESS_USER_PASSWORD_HASH}}
CYPRESS_USER_API_KEY_HASH={{CYPRESS_USER_API_KEY_HASH}}
FULL_CALENDAR_LICENCE={{FULL_CALENDAR_LICENCE}}
NICE2_REPO_BASE_PATH={{NICE2_REPO_BASE_PATH}}
