HIBERNATE_MAIN_SERVERNAME={{HIBERNATE_MAIN_SERVERNAME}}
HIBERNATE_MAIN_USER={{HIBERNATE_MAIN_USER}}
HIBERNATE_MAIN_PASSWORD={{HIBERNATE_MAIN_PASSWORD}}
HIBERNATE_MAIN_DATABASENAME={{HIBERNATE_MAIN_DATABASENAME}}
HIBERNATE_MAIN_SSLMODE=disable
NICE2_REPO={{NICE2_REPO}}
CYPRESS_PRINCIPAL_PASSWORD_HASH={{CYPRESS_PRINCIPAL_PASSWORD_HASH}}
CYPRESS_PRINCIPAL_API_KEY_HASH={{CYPRESS_PRINCIPAL_API_KEY_HASH}}
