import editableValueFactory from './editableValueFactory'

export default {
  'ch.tocco.nice2.model.form.components.Form': null,
  'ch.tocco.nice2.model.form.components.Template': null,
  'ch.tocco.nice2.model.form.components.action.Action': null,
  'ch.tocco.nice2.model.form.components.action.ActionSeparator': null,
  'ch.tocco.nice2.model.form.components.composite.LocationField': null,
  'ch.tocco.nice2.model.form.components.layout.HorizontalBox': null,
  'ch.tocco.nice2.model.form.components.layout.VerticalBox': null,
  'ch.tocco.nice2.model.form.components.navigation.IteratorComponent': null,
  'ch.tocco.nice2.model.form.components.simple.BirthDateField': editableValueFactory('birthdate'),
  'ch.tocco.nice2.model.form.components.simple.Checkbox': editableValueFactory('boolean'),
  'ch.tocco.nice2.model.form.components.simple.CodeField': editableValueFactory('text'),
  'ch.tocco.nice2.model.form.components.simple.ConstantField': null,
  'ch.tocco.nice2.model.form.components.simple.CreatePasswordField': null,
  'ch.tocco.nice2.model.form.components.simple.CustomDataField': null,
  'ch.tocco.nice2.model.form.components.simple.DataAmountField': editableValueFactory('number'),
  'ch.tocco.nice2.model.form.components.simple.DateField': editableValueFactory('date'),
  'ch.tocco.nice2.model.form.components.simple.DatetimeField': editableValueFactory('datetime'),
  'ch.tocco.nice2.model.form.components.simple.DescriptionField': null,
  'ch.tocco.nice2.model.form.components.simple.DisplayExpressionFieldFacade': null,
  'ch.tocco.nice2.model.form.components.simple.DisplayField': null,
  'ch.tocco.nice2.model.form.components.simple.DocumentField': editableValueFactory('document'),
  'ch.tocco.nice2.model.form.components.simple.DurationField': null,
  'ch.tocco.nice2.model.form.components.simple.EmailField': editableValueFactory('email'),
  'ch.tocco.nice2.model.form.components.simple.HtmlField': editableValueFactory('text'),
  'ch.tocco.nice2.model.form.components.simple.ImageField': editableValueFactory('document'),
  'ch.tocco.nice2.model.form.components.simple.LoginField': editableValueFactory('string'),
  'ch.tocco.nice2.model.form.components.simple.MoneyAmountField': editableValueFactory('number'),
  'ch.tocco.nice2.model.form.components.simple.MultiRemoteField': editableValueFactory('multi-remote'),
  'ch.tocco.nice2.model.form.components.simple.MultiSelectBox': editableValueFactory('multi-select'),
  'ch.tocco.nice2.model.form.components.simple.NamedUploadField': editableValueFactory('document'),
  'ch.tocco.nice2.model.form.components.simple.NumberField': editableValueFactory('number'),
  'ch.tocco.nice2.model.form.components.simple.PasswordField': null,
  'ch.tocco.nice2.model.form.components.simple.PathField': null,
  'ch.tocco.nice2.model.form.components.simple.PercentField': editableValueFactory('number'),
  'ch.tocco.nice2.model.form.components.simple.PhoneField': editableValueFactory('phone'),
  'ch.tocco.nice2.model.form.components.simple.PulldownDateField': editableValueFactory('date'),
  'ch.tocco.nice2.model.form.components.simple.RangeField': {
    'number': editableValueFactory('number'),
    'counter': editableValueFactory('number'),
    'date': editableValueFactory('date-range'),
    'birthdate': editableValueFactory('date-range')
  },
  'ch.tocco.nice2.model.form.components.simple.RemoteField': editableValueFactory('remote'),
  'ch.tocco.nice2.model.form.components.simple.SearchFilterField': editableValueFactory('search-filter'),
  'ch.tocco.nice2.model.form.components.simple.SingleSelectBox': editableValueFactory('single-select'),
  'ch.tocco.nice2.model.form.components.simple.TextArea': editableValueFactory('text'),
  'ch.tocco.nice2.model.form.components.simple.TextField': editableValueFactory('string'),
  'ch.tocco.nice2.model.form.components.simple.TimeField': null,
  'ch.tocco.nice2.model.form.components.simple.UploadField': editableValueFactory('document'),
  'ch.tocco.nice2.model.form.components.simple.UrlField': editableValueFactory('url'),
  'ch.tocco.nice2.model.form.components.simple.UuidField': editableValueFactory('string'),
  'ch.tocco.nice2.model.form.components.table.Column': null,
  'ch.tocco.nice2.model.form.components.table.Table': null
}
