# Github action that automatically creates a pullrequest for "releasing/" and "cherry-picking/" branches.
# Reads destination branch out of pullrequest branch name.
# For example the pullrequest "releasing/_nice-releases/30_auto-1639553335" as as destination branch "nice-releases/30"

name: Auto Create Pull Request

on:
  push:
    branches:
      - "releasing/**"
      - "cherry-picking/**"

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Read and set target branch
        id: get_target_branch
        shell: bash
        run: echo "##[set-output name=target_branch;]$(echo ${GITHUB_REF} | sed 's/.*_\(.*\)_.*/\1/')"
      - name: pull-request
        uses: repo-sync/pull-request@v2.6
        with:
          destination_branch: ${{ steps.get_target_branch.outputs.target_branch }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
